### PR TITLE
@hooks/useForceUpdate useForceUpdate hook added

### PR DESCRIPTION
**Pull request by sina-byn**
a hook to force a render in react - useful when working with deeply nested objects or arrays

### CODE REVIEW

**Comment by erfunit** [comment]
I really thank you for your contribution❤️
I'll appreciate if you take a look at [CONTRIBUTING.md](https://github.com/useTermite/useTermite/blob/main/CONTRIBUTING.md), just missed 2 little steps (second and third).
and don't forget to follow the format of [readme.md](https://github.com/useTermite/useTermite/blob/main/docs/README.md) documentation to add your new custom hook

**Review by erfunit — COMMENTED** [review]
That would be really useful 👍

**Comment by sina-byn** [comment]
Do you consider a new hook to be a minor version?
I have quite a few ideas on how to imporve the codebase and include more custom hooks is there any other way to get in touch with you instead of just creating new issues?
@erfunit

**Comment by erfunit** [comment]
You can just get in touch with me on telegram if you wish [@erfundev](https://t.me/erfundev) 🤍

**Comment by erfunit** [comment]
Yeah it should be a new minor version.
@sina-byn

**Comment by sina-byn** [comment]
@erfunit ok will take care of it in a few hours

**Pull request closed without merging**
